documentation:
  - changed-files:
      - "*.md"
      - ".github/ISSUE_TEMPLATE/*.md"
      - "README.md"
      - "CONTRIBUTING.md"

feature:
  - changed-files:
      - "src/cli/*"
      - "src/core/*"

renderer:
  - changed-files:
      - "src/renderer/*"

test:
  - changed-files:
      - "**/*.test.ts"
      - "**/*.e2e.ts"
      - "playwright.config.ts"
